### ISSUE TITLE
How to use this generator? what does this do?

### ISSUE THREAD

**Issue by shiamalon** [bigbug-studio/generator-jhipster-elasticsearch-rest-client#1]
Are you install? the generator use elasticsearch 9200 port, not use 9300 port

**Comment by WeijianHuang** [comment]
Are you install? the generator use elasticsearch 9200 port, not use 9300 port

**Comment by ChihoSin** [comment]
Just a elasticsearch rest client for jhispter, this client is for version 5+, but is working at version <5.
